### ISSUE TITLE
Learn Apache Maven

### ISSUE THREAD

**Issue by amihaiemil** [r-a-cristian-93/Issue-Tracking-Application#2]
I see you wrote your own shell script for compiling Java classes. You also have a lib folder where you put the dependencies.
 
In real life projects, we use [Maven](https://maven.apache.org/). Maven is the most widely used build tool in the industry.

"building" a project usually means:

- Fetching dependencies (usually from the Maven Central Repository)
- Compiling the code
- Running tests
- Packaging the application as jar, war or ear.

You won't need to write your own compiling script anymore and Maven will take care of the project's dependencies automatically.

**Comment by r-a-cristian-93** [comment]
> I see you wrote your own shell script for compiling Java classes. You also have a lib folder where you put the dependencies.
> 
> In real life projects, we use [Maven](https://maven.apache.org/). Maven is the most widely used build tool in the industry.
> 
> "building" a project usually means:
> 
>     * Fetching dependencies (usually from the Maven Central Repository)
> 
>     * Compiling the code
> 
>     * Running tests
> 
>     * Packaging the application as jar, war or ear.
> 
> 
> You won't need to write your own compiling script anymore and Maven will take care of the project's dependencies automatically.

**Comment by r-a-cristian-93** [comment]
Thx, i will make that my next step, it actually sucked doing that and i hope that Maven will help.
